### ISSUE TITLE
HTML in php code break the code

### ISSUE THREAD

**Issue by tlito** [alexgorbatchev/syntaxhighlighter#23]
the brushes php or even plain break the code in the line:

![ttttt2](https://cloud.githubusercontent.com/assets/11997227/8701885/1ab75cfc-2b1d-11e5-932d-454c3cdbd0b4.png)

show this:
<img src="http://storage2.static.itmages.ru/i/15/0715/h_1436973094_2891528_ac61d0145d.png">

**Comment by monteiroiale** [comment]
me too

**Comment by alexgorbatchev** [comment]
https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Caveats
